services:
  mysql-server: #This is the service name for the MySQL database
    labels:
      - "project=giveaway-app"
      - "purpose=database"
      - "version=v0.01"
      - "description=MySQL database for giveaway application"

    image: mysql
    container_name: mysql-container

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      
    ports:
      - "4000:3306"
    
    volumes:
      - giveaway-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
    networks:
      - giveaway-net

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  giveaway-web:
#By using the build context, you can build the Docker image from a Dockerfile in the current directory.
    #build: .
    #container_name: giveaway-web-container
    labels:
      - "project=giveaway-app"
      - "purpose=web-app-frontend"
      - "version=v0.01"
      - "author=Karan_Negi"
      - "description=Giveaway web application"

    image: devopskarannegi/devops-pipeline-workflow:v0.01
    container_name: giveaway-web-conatiner
    
    environment:
      - DB_HOST=mysql-server
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

    ports:
      - "3000:3000"

    volumes:
      - giveaway-data:/var/lib/giveaway

    networks:
      - giveaway-net

    depends_on:
      mysql-server:
        condition: service_healthy

    #deploy:
      #replicas: 2

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  giveaway-data:
    external: true
    
networks:
  giveaway-net:
   driver: bridge
   external: true
  